// Code generated by go-enum-encoding; DO NOT EDIT.

package color

import (
	"testing"
)

func TestColorString_String(t *testing.T) {
	values := []ColorString{RedS, GreenS, BlueS}
	tags := []string{"red", "green", "blue"}

	for i := range values {
		if values[i].String() != tags[i] {
			t.Errorf("got(%s) != exp(%s)", values[i].String(), tags[i])
		}
	}
}

func BenchmarkColorString_String(b *testing.B) {
	var v string
	for i := 0; i < b.N; i++ {
		for _, c := range []ColorString{RedS, GreenS, BlueS} {
			v = c.String()
		}
	}
	if len(v) > 1000 {
		b.Fatal("noop")
	}
}
