// Code generated by go-enum-encoding DO NOT EDIT
package color

import "errors"

var ErrUnknownColor = errors.New("unknown Color")

func (s *Color) UnmarshalText(text []byte) error {
	switch string(text) {
	case "":
		*s = UndefinedColor
	case "red":
		*s = Red
	case "green":
		*s = Green
	case "blue":
		*s = Blue
	default:
		return ErrUnknownColor
	}
	return nil
}

var json_bytes_Color = [...][]byte{[]byte(""), []byte("red"), []byte("green"), []byte("blue")}

func (s Color) MarshalText() ([]byte, error) {
	switch s {
	case UndefinedColor:
		return json_bytes_Color[0], nil
	case Red:
		return json_bytes_Color[1], nil
	case Green:
		return json_bytes_Color[2], nil
	case Blue:
		return json_bytes_Color[3], nil
	default:
		return nil, ErrUnknownColor
	}
}
