// Code generated by go-enum-encoding DO NOT EDIT.

package color

import "errors"

var ErrUnknownColorString = errors.New("unknown ColorString")

func (s *ColorString) UnmarshalText(text []byte) error {
	switch string(text) {
	case "red":
		*s = RedS
	case "green":
		*s = GreenS
	case "blue":
		*s = BlueS
	default:
		return ErrUnknownColorString
	}
	return nil
}

var json_bytes_ColorString = [...][]byte{[]byte("red"), []byte("green"), []byte("blue")}

func (s ColorString) MarshalText() ([]byte, error) {
	switch s {
	case RedS:
		return json_bytes_ColorString[0], nil
	case GreenS:
		return json_bytes_ColorString[1], nil
	case BlueS:
		return json_bytes_ColorString[2], nil
	default:
		return nil, ErrUnknownColorString
	}
}

func (s ColorString) String() string {
	b, _ := s.MarshalText()
	return string(b)
}
