// Code generated by go-enum-encoding DO NOT EDIT
package color

import "errors"

var ErrUnknownColor2 = errors.New("unknown Color2")

func (s *Color2) UnmarshalText(text []byte) error {
	switch string(text) {
	case "":
		*s = UndefinedColor
	case "red":
		*s = Red
	case "":
		*s = UndefCurrency
	case "SGD":
		*s = SGD
	case "USD":
		*s = USD
	default:
		return ErrUnknownColor2
	}
	return nil
}

var json_bytes_Color2 = [...][]byte{[]byte(""), []byte("red"), []byte(""), []byte("SGD"), []byte("USD")}

func (s Color2) MarshalText() ([]byte, error) {
	switch s {
	case UndefinedColor:
		return json_bytes_Color2[0], nil
	case Red:
		return json_bytes_Color2[1], nil
	case UndefCurrency:
		return json_bytes_Color2[2], nil
	case SGD:
		return json_bytes_Color2[3], nil
	case USD:
		return json_bytes_Color2[4], nil
	default:
		return nil, ErrUnknownColor2
	}
}
