// Code generated by go-enum-encoding DO NOT EDIT
package color

import "errors"

var ErrUnknownCurrency = errors.New("unknown Currency")

var vals_Currency = map[Currency][]byte{
	UndefinedCurrency: []byte(""),
	SGD:               []byte("SGD"),
	USD:               []byte("USD"),
	GBP:               []byte("GBP"),
	KRW:               []byte("KRW"),
	HKD:               []byte("HKD"),
	JPY:               []byte("JPY"),
	MYR:               []byte("MYR"),
	BHT:               []byte("BHT"),
	THC:               []byte("THC"),
	CBD:               []byte("CBD"),
	XYZ:               []byte("XYZ"),
}

var vals_inv_Currency = map[string]Currency{
	"":    UndefinedCurrency,
	"SGD": SGD,
	"USD": USD,
	"GBP": GBP,
	"KRW": KRW,
	"HKD": HKD,
	"JPY": JPY,
	"MYR": MYR,
	"BHT": BHT,
	"THC": THC,
	"CBD": CBD,
	"XYZ": XYZ,
}

func (s *Currency) UnmarshalText(text []byte) error {
	var ok bool
	if *s, ok = vals_inv_Currency[string(text)]; !ok {
		return ErrUnknownCurrency
	}
	return nil
}

func (s Currency) MarshalText() ([]byte, error) { return vals_Currency[s], nil }
