// Code generated by go-enum-encoding; DO NOT EDIT.

package color

import "errors"

var ErrUnknownCurrencyStringCustom = errors.New("unknown CurrencyStringCustom")

var value_to_bytes_CurrencyStringCustom = map[CurrencyStringCustom][]byte{
	UndefinedCurrencySC: []byte(""),
	SGDSC:               []byte("SGD"),
	USDSC:               []byte("USD"),
	GBPSC:               []byte("GBP"),
	KRWSC:               []byte("KRW"),
	HKDSC:               []byte("HKD"),
	JPYSC:               []byte("JPY"),
	MYRSC:               []byte("MYR"),
	BHTSC:               []byte("BHT"),
	THCSC:               []byte("THC"),
	CBDSC:               []byte("CBD"),
	XYZSC:               []byte("XYZ"),
}

var string_to_value_CurrencyStringCustom = map[string]CurrencyStringCustom{
	"":    UndefinedCurrencySC,
	"SGD": SGDSC,
	"USD": USDSC,
	"GBP": GBPSC,
	"KRW": KRWSC,
	"HKD": HKDSC,
	"JPY": JPYSC,
	"MYR": MYRSC,
	"BHT": BHTSC,
	"THC": THCSC,
	"CBD": CBDSC,
	"XYZ": XYZSC,
}

func (s *CurrencyStringCustom) UnmarshalTextName(text []byte) error {
	var ok bool
	if *s, ok = string_to_value_CurrencyStringCustom[string(text)]; !ok {
		return ErrUnknownCurrencyStringCustom
	}
	return nil
}

func (s CurrencyStringCustom) MarshalTextName() ([]byte, error) {
	return value_to_bytes_CurrencyStringCustom[s], nil
}

var value_to_string_CurrencyStringCustom = map[CurrencyStringCustom]string{
	UndefinedCurrencySC: "",
	SGDSC:               "SGD",
	USDSC:               "USD",
	GBPSC:               "GBP",
	KRWSC:               "KRW",
	HKDSC:               "HKD",
	JPYSC:               "JPY",
	MYRSC:               "MYR",
	BHTSC:               "BHT",
	THCSC:               "THC",
	CBDSC:               "CBD",
	XYZSC:               "XYZ",
}

func (s CurrencyStringCustom) StringName() string { return value_to_string_CurrencyStringCustom[s] }
