// Code generated by go-enum-encoding DO NOT EDIT
package main

import "errors"

var ErrUnknownNoUndefined = errors.New("unknown NoUndefined")

var vals_NoUndefined = map[NoUndefined]string{
	BlueNoUndefined: "blue",
	RedNoUndefined:  "red",
}

var vals_inv_NoUndefined = map[string]NoUndefined{
	"blue": BlueNoUndefined,
	"red":  RedNoUndefined,
}

func (s *NoUndefined) UnmarshalText(text []byte) error {
	var ok bool
	if *s, ok = vals_inv_NoUndefined[string(text)]; !ok {
		return ErrUnknownNoUndefined
	}
	return nil
}

func (s NoUndefined) MarshalText() ([]byte, error) { return []byte(s.String()), nil }

func (s NoUndefined) String() string { return vals_NoUndefined[s] }
