// Code generated by go-enum-encoding; DO NOT EDIT.

package image

import (
	"encoding/json"
	"errors"
	"fmt"
	"slices"
	"testing"
)

func ExampleSize_MarshalText() {
	for _, v := range []Size{UndefinedSize, Small, Large, XLarge} {
		b, _ := v.MarshalText()
		fmt.Printf("%s ", string(b))
	}
	// Output:  small large xlarge
}

func ExampleSize_UnmarshalText() {
	for _, s := range []string{"", "small", "large", "xlarge"} {
		var v Size
		if err := (&v).UnmarshalText([]byte(s)); err != nil {
			fmt.Println(err)
		}
	}
}

func TestSize_MarshalText_UnmarshalText(t *testing.T) {
	for _, v := range []Size{UndefinedSize, Small, Large, XLarge} {
		b, err := v.MarshalText()
		if err != nil {
			t.Errorf("cannot encode: %s", err)
		}

		var d Size
		if err := (&d).UnmarshalText(b); err != nil {
			t.Errorf("cannot decode: %s", err)
		}

		if d != v {
			t.Errorf("exp(%v) != got(%v)", v, d)
		}
	}

	t.Run("when unknown value, then error", func(t *testing.T) {
		s := `something`
		var v Size
		err := (&v).UnmarshalText([]byte(s))
		if err == nil {
			t.Error("must be error")
		}
		if !errors.Is(err, ErrUnknownSize) {
			t.Error("wrong error", err)
		}
	})
}

func TestSize_JSON(t *testing.T) {
	type V struct {
		Values []Size `json:"values"`
	}

	values := []Size{UndefinedSize, Small, Large, XLarge}

	var v V
	s := `{"values":["","small","large","xlarge"]}`
	json.Unmarshal([]byte(s), &v)

	if len(v.Values) != len(values) {
		t.Errorf("cannot decode: %d", len(v.Values))
	}
	if !slices.Equal(v.Values, values) {
		t.Errorf("wrong decoded: %v", v.Values)
	}

	b, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("cannot encode: %s", err)
	}
	if string(b) != s {
		t.Errorf("wrong encoded: %s != %s", string(b), s)
	}

	t.Run("when unknown value, then error", func(t *testing.T) {
		s := `{"values":["something"]}`
		var v V
		err := json.Unmarshal([]byte(s), &v)
		if err == nil {
			t.Error("must be error")
		}
		if !errors.Is(err, ErrUnknownSize) {
			t.Error("wrong error", err)
		}
	})
}

func BenchmarkSize_MarshalText(b *testing.B) {
	for b.Loop() {
		for _, c := range []Size{UndefinedSize, Small, Large, XLarge} {
			if _, err := c.MarshalText(); err != nil {
				b.Fatal("empty")
			}
		}
	}
}

func BenchmarkSize_UnmarshalText(b *testing.B) {
	var x Size
	for b.Loop() {
		for _, c := range []string{"", "small", "large", "xlarge"} {
			if err := x.UnmarshalText([]byte(c)); err != nil {
				b.Fatal("cannot decode")
			}
		}
	}
}

func TestSize_String(t *testing.T) {
	values := []Size{UndefinedSize, Small, Large, XLarge}
	tags := []string{"", "small", "large", "xlarge"}

	for i := range values {
		if s := values[i].String(); s != tags[i] {
			t.Error(s, tags[i])
		}
	}
}

func BenchmarkSize_String(b *testing.B) {
	for b.Loop() {
		for _, c := range []Size{UndefinedSize, Small, Large, XLarge} {
			c.String()
		}
	}
}
