// Code generated by go-enum-encoding; DO NOT EDIT.

package image

import "errors"

var ErrUnknownSize = errors.New("unknown Size")

func (s *Size) UnmarshalText(text []byte) error {
	switch string(text) {
	case "":
		*s = UndefinedSize
	case "small":
		*s = Small
	case "large":
		*s = Large
	case "xlarge":
		*s = XLarge
	default:
		return ErrUnknownSize
	}
	return nil
}

var seq_bytes_Size = [...][]byte{[]byte(""), []byte("small"), []byte("large"), []byte("xlarge")}

func (s Size) MarshalText() ([]byte, error) {
	switch s {
	case UndefinedSize:
		return seq_bytes_Size[0], nil
	case Small:
		return seq_bytes_Size[1], nil
	case Large:
		return seq_bytes_Size[2], nil
	case XLarge:
		return seq_bytes_Size[3], nil
	default:
		return nil, ErrUnknownSize
	}
}

var seq_string_Size = [...]string{"", "small", "large", "xlarge"}

func (s Size) String() string {
	switch s {
	case UndefinedSize:
		return seq_string_Size[0]
	case Small:
		return seq_string_Size[1]
	case Large:
		return seq_string_Size[2]
	case XLarge:
		return seq_string_Size[3]
	default:
		return ""
	}
}
