// Code generated by go-enum-encoding DO NOT EDIT
package color

import "errors"

var ErrUnknownSize = errors.New("unknown Size")

func (s *Size) UnmarshalText(text []byte) error {
	switch string(text) {
	case "":
		*s = UndefinedSize
	case "small":
		*s = Small
	case "large":
		*s = Large
	case "xlarge":
		*s = XLarge
	default:
		return ErrUnknownSize
	}
	return nil
}

var json_bytes_Size = [...][]byte{[]byte(""), []byte("small"), []byte("large"), []byte("xlarge")}

func (s Size) MarshalText() ([]byte, error) {
	switch s {
	case UndefinedSize:
		return json_bytes_Size[0], nil
	case Small:
		return json_bytes_Size[1], nil
	case Large:
		return json_bytes_Size[2], nil
	case XLarge:
		return json_bytes_Size[3], nil
	default:
		return nil, ErrUnknownSize
	}
}
