// Code generated by go-enum-encoding DO NOT EDIT
package color

import "errors"

var ErrUnknownColor = errors.New("unknown Color")

var vals_Color = map[Color]string{
	UndefinedColor: "",
	Red:            "red",
	Green:          "green",
	Blue:           "blue",
}

var vals_inv_Color = map[string]Color{
	"":      UndefinedColor,
	"red":   Red,
	"green": Green,
	"blue":  Blue,
}

func (s *Color) UnmarshalText(text []byte) error {
	var ok bool
	if *s, ok = vals_inv_Color[string(text)]; !ok {
		return ErrUnknownColor
	}
	return nil
}

func (s Color) MarshalText() ([]byte, error) { return []byte(s.String()), nil }

func (s Color) String() string { return vals_Color[s] }
