// Code generated by go-enum-encoding DO NOT EDIT
package main

import "errors"

var ErrUnknownColor = errors.New("unknown Color")

var vals_Color = map[Color]string{
	Blue:  "blue",
	Green: "green",
	Red:   "red",
}

var vals_inv_Color = map[string]Color{
	"blue":  Blue,
	"green": Green,
	"red":   Red,
}

func (s *Color) UnmarshalText(text []byte) error {
	*s = vals_inv_Color[string(text)]
	if *s == Undefined {
		return ErrUnknownColor
	}
	return nil
}

func (s Color) MarshalText() ([]byte, error) { return []byte(s.String()), nil }

func (s Color) String() string { return vals_Color[s] }
