// Code generated by go-enum-encoding DO NOT EDIT
package color

import "errors"

var ErrUnknownCurrency2 = errors.New("unknown Currency2")

func (s *Currency2) UnmarshalText(text []byte) error {
	switch string(text) {
	case "":
		*s = UndefCurrency
	case "SGD":
		*s = SGD
	case "USD":
		*s = USD
	default:
		return ErrUnknownCurrency2
	}
	return nil
}

var json_bytes_Currency2 = [...][]byte{[]byte(""), []byte("SGD"), []byte("USD")}

func (s Currency2) MarshalText() ([]byte, error) {
	switch s {
	case UndefCurrency:
		return json_bytes_Currency2[0], nil
	case SGD:
		return json_bytes_Currency2[1], nil
	case USD:
		return json_bytes_Currency2[2], nil
	default:
		return nil, ErrUnknownCurrency2
	}
}
