// Code generated by go-enum-encoding; DO NOT EDIT.

package color

import (
	"errors"
	"testing"
)

func TestCurrency2_MarshalText_UnmarshalText(t *testing.T) {
	for _, v := range []Currency2{UndefCurrency2, SGD2, USD2} {
		b, err := v.MarshalText()
		if err != nil {
			t.Errorf("cannot encode: %s", err)
		}

		var d Currency2
		if err := (&d).UnmarshalText(b); err != nil {
			t.Errorf("cannot decode: %s", err)
		}

		if d != v {
			t.Errorf("exp(%v) != got(%v)", v, d)
		}
	}

	t.Run("when unknown value, then error", func(t *testing.T) {
		s := `something`
		var v Currency2
		err := (&v).UnmarshalText([]byte(s))
		if err == nil {
			t.Errorf("must be error")
		}
		if !errors.Is(err, ErrUnknownCurrency2) {
			t.Errorf("wrong error: %s", err)
		}
	})
}

func BenchmarkCurrency2_MarshalText(b *testing.B) {
	var v []byte
	var err error
	for i := 0; i < b.N; i++ {
		for _, c := range []Currency2{UndefCurrency2, SGD2, USD2} {
			if v, err = c.MarshalText(); err != nil {
				b.Fatal("empty")
			}
		}
	}
	if len(v) > 1000 {
		b.Fatal("noop")
	}
}

func BenchmarkCurrency2_UnmarshalText(b *testing.B) {
	var x Currency2
	for i := 0; i < b.N; i++ {
		for _, c := range []string{"", "SGD", "USD"} {
			if err := x.UnmarshalText([]byte(c)); err != nil {
				b.Fatal("cannot decode")
			}
		}
	}
}
