// Code generated by go-enum-encoding; DO NOT EDIT.

package color

import (
	"testing"
)

func TestCurrencyString_String(t *testing.T) {
	values := []CurrencyString{UndefinedCurrencyS, SGDS, USDS, GBPS, KRWS, HKDS, JPYS, MYRS, BHTS, THCS, CBDS, XYZS}
	tags := []string{"", "SGD", "USD", "GBP", "KRW", "HKD", "JPY", "MYR", "BHT", "THC", "CBD", "XYZ"}

	for i := range values {
		if values[i].String() != tags[i] {
			t.Errorf("got(%s) != exp(%s)", values[i].String(), tags[i])
		}
	}
}

func BenchmarkCurrencyString_String(b *testing.B) {
	var v string
	for i := 0; i < b.N; i++ {
		for _, c := range []CurrencyString{UndefinedCurrencyS, SGDS, USDS, GBPS, KRWS, HKDS, JPYS, MYRS, BHTS, THCS, CBDS, XYZS} {
			v = c.String()
		}
	}
	if len(v) > 1000 {
		b.Fatal("noop")
	}
}
