// Code generated by go-enum-encoding; DO NOT EDIT.

package color

import (
	"errors"
	"testing"
)

func TestCurrencyStringCustom_MarshalTextName_UnmarshalTextName(t *testing.T) {
	for _, v := range []CurrencyStringCustom{UndefinedCurrencySC, SGDSC, USDSC, GBPSC, KRWSC, HKDSC, JPYSC, MYRSC, BHTSC, THCSC, CBDSC, XYZSC} {
		b, err := v.MarshalTextName()
		if err != nil {
			t.Errorf("cannot encode: %s", err)
		}

		var d CurrencyStringCustom
		if err := (&d).UnmarshalTextName(b); err != nil {
			t.Errorf("cannot decode: %s", err)
		}

		if d != v {
			t.Errorf("exp(%v) != got(%v)", v, d)
		}
	}

	t.Run("when unknown value, then error", func(t *testing.T) {
		s := `something`
		var v CurrencyStringCustom
		err := (&v).UnmarshalTextName([]byte(s))
		if err == nil {
			t.Errorf("must be error")
		}
		if !errors.Is(err, ErrUnknownCurrencyStringCustom) {
			t.Errorf("wrong error: %s", err)
		}
	})
}

func BenchmarkCurrencyStringCustom_MarshalTextName(b *testing.B) {
	var v []byte
	var err error
	for i := 0; i < b.N; i++ {
		for _, c := range []CurrencyStringCustom{UndefinedCurrencySC, SGDSC, USDSC, GBPSC, KRWSC, HKDSC, JPYSC, MYRSC, BHTSC, THCSC, CBDSC, XYZSC} {
			if v, err = c.MarshalTextName(); err != nil {
				b.Fatal("empty")
			}
		}
	}
	if len(v) > 1000 {
		b.Fatal("noop")
	}
}

func BenchmarkCurrencyStringCustom_UnmarshalTextName(b *testing.B) {
	var x CurrencyStringCustom
	for i := 0; i < b.N; i++ {
		for _, c := range []string{"", "SGD", "USD", "GBP", "KRW", "HKD", "JPY", "MYR", "BHT", "THC", "CBD", "XYZ"} {
			if err := x.UnmarshalTextName([]byte(c)); err != nil {
				b.Fatal("cannot decode")
			}
		}
	}
}
