// Code generated by go-enum-encoding; DO NOT EDIT.

package color

import "errors"

var ErrUnknownColorString = errors.New("unknown ColorString")

func (s *ColorString) UnmarshalText(text []byte) error {
	switch string(text) {
	case "red":
		*s = RedS
	case "green":
		*s = GreenS
	case "blue":
		*s = BlueS
	default:
		return ErrUnknownColorString
	}
	return nil
}

var seq_bytes_ColorString = [...][]byte{[]byte("red"), []byte("green"), []byte("blue")}

func (s ColorString) MarshalText() ([]byte, error) {
	switch s {
	case RedS:
		return seq_bytes_ColorString[0], nil
	case GreenS:
		return seq_bytes_ColorString[1], nil
	case BlueS:
		return seq_bytes_ColorString[2], nil
	default:
		return nil, ErrUnknownColorString
	}
}

var seq_string_ColorString = [...]string{"red", "green", "blue"}

func (s ColorString) String() string {
	switch s {
	case RedS:
		return seq_string_ColorString[0]
	case GreenS:
		return seq_string_ColorString[1]
	case BlueS:
		return seq_string_ColorString[2]
	default:
		return ""
	}
}
