// Code generated by go-enum-encoding; DO NOT EDIT.

package color

import (
	"testing"
)

func TestCurrencyStringCustom_StringName(t *testing.T) {
	values := []CurrencyStringCustom{UndefinedCurrencySC, SGDSC, USDSC, GBPSC, KRWSC, HKDSC, JPYSC, MYRSC, BHTSC, THCSC, CBDSC, XYZSC}
	tags := []string{"", "SGD", "USD", "GBP", "KRW", "HKD", "JPY", "MYR", "BHT", "THC", "CBD", "XYZ"}

	for i := range values {
		if values[i].StringName() != tags[i] {
			t.Errorf("got(%s) != exp(%s)", values[i].StringName(), tags[i])
		}
	}
}

func BenchmarkCurrencyStringCustom_StringName(b *testing.B) {
	var v string
	for i := 0; i < b.N; i++ {
		for _, c := range []CurrencyStringCustom{UndefinedCurrencySC, SGDSC, USDSC, GBPSC, KRWSC, HKDSC, JPYSC, MYRSC, BHTSC, THCSC, CBDSC, XYZSC} {
			v = c.StringName()
		}
	}
	if len(v) > 1000 {
		b.Fatal("noop")
	}
}
