name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: test
        env:
          GOCOVERPROFILE: coverage.out
        run: go test ./...

      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v4.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
